# Generated by Django 2.1.7 on 2019-03-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'neutral'), ('tired', 'tired'), ('angry', 'Angry'), ('sad', 'Sad')], max_length=64)),
                ('time_of_day', models.CharField(choices=[('NA', 'Not Applicable'), ('MO', 'Morning'), ('AF', 'Afternoon'), ('EV', 'Evening')], max_length=2)),
                ('social_context', models.CharField(choices=[('NA', 'Not Applicable'), ('AC', 'Academic'), ('SO', 'Social'), ('CO', 'Context'), ('WO', 'Work')], max_length=2)),
                ('interaction_medium', models.CharField(choices=[('NA', 'Not Applicable'), ('IP', 'In Person'), ('ON', 'Online'), ('PH', 'Over the Phone')], max_length=2)),
                ('other_loggable_text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rec_typ', models.CharField(choices=[('PO', 'Positive'), ('NE', 'Negative'), ('AV', 'Avoidance')], max_length=2)),
                ('recommendation', models.CharField(max_length=128)),
                ('about_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_person', to='api.Person')),
                ('recommend_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_person', to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_typ', models.CharField(choices=[('WO', 'Worked'), ('DW', "Doesn't Work"), ('NE', 'Neutral')], max_length=2)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tied_recommendation', to='api.Recommendation')),
            ],
        ),
        migrations.AddField(
            model_name='logentry',
            name='loggee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loggee_person', to='api.Person'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='logger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_person', to='api.Person'),
        ),
    ]
