# Generated by Django 2.1.7 on 2019-03-21 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='interaction_medium',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('IP', 'In Person'), ('ON', 'Online'), ('PH', 'Over The Phone')], max_length=2),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='reaction',
            field=models.CharField(choices=[('ha', 'Happy'), ('ne', 'Neutral'), ('ti', 'Tired'), ('an', 'Angry'), ('sa', 'Sad')], max_length=2),
        ),
    ]
