# Generated by Django 2.1.7 on 2019-03-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190321_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='logentry',
            name='loggee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loggee_person', to='api.Friend'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='logger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_person', to='api.User'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='social_context',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('AC', 'Academic'), ('SO', 'Social'), ('OC', 'Other'), ('WO', 'Work')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='about_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_person', to='api.Friend'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommend_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_person', to='api.User'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
