# Generated by Django 2.1.7 on 2019-04-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190325_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='reaction',
            field=models.CharField(choices=[('HA', 'Happy'), ('NE', 'Neutral'), ('TI', 'Tired'), ('AN', 'Angry'), ('SA', 'Sad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='rec_typ',
            field=models.CharField(choices=[('PO', 'Positive'), ('NE', 'Negative'), ('AV', 'Avoidance'), ('GE', 'Generic')], max_length=2),
        ),
    ]
