# Generated by Django 2.1.7 on 2019-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190413_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='rec_description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
