# Generated by Django 2.1.7 on 2019-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recommendation_rec_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='content_class',
            field=models.CharField(choices=[('SM', 'Small Talk'), ('OP', 'One Personal'), ('BP', 'Both Personal')], default='SM', max_length=2),
            preserve_default=False,
        ),
    ]
