# Generated by Django 2.1.7 on 2019-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_logentry_content_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_generic_recs',
            field=models.BooleanField(default=False),
        ),
    ]
