# Generated by Django 2.1.7 on 2019-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190416_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='fb_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='from_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='content_class',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('SM', 'Small Talk'), ('OP', 'One Personal'), ('BP', 'Both Personal')], max_length=2),
        ),
    ]
