# Generated by Django 2.1.7 on 2019-04-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190417_1905'),
        ('api', '0009_auto_20190419_1932'),
    ]

    operations = [
    ]
